//! aura.lock (SPEC §5.2, D8): фиксация точных версий registry-модулей + integrity-хэш.

use std::collections::BTreeMap;

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LockEntry {
    /// Точная версия без префикса `v`, например "1.2.9".
    pub version: String,
    /// "sha256-<hex>" содержимого файла модуля.
    pub integrity: String,
}

#[derive(Debug, Default, Clone)]
pub struct Lockfile {
    /// BTreeMap — детерминированный порядок записи.
    pub entries: BTreeMap<String, LockEntry>,
    /// Появились новые/обновлённые записи — файл нужно перезаписать (кроме --frozen).
    pub dirty: bool,
}

impl Lockfile {
    pub fn parse(text: &str) -> Result<Self, String> {
        let value: toml::Value = toml::from_str(text).map_err(|e| e.to_string())?;
        let mut entries = BTreeMap::new();
        if let Some(modules) = value.get("modules").and_then(|m| m.as_table()) {
            for (path, entry) in modules {
                let version = entry
                    .get("version")
                    .and_then(|v| v.as_str())
                    .ok_or_else(|| format!("lock entry '{path}': missing version"))?;
                let integrity = entry
                    .get("integrity")
                    .and_then(|v| v.as_str())
                    .ok_or_else(|| format!("lock entry '{path}': missing integrity"))?;
                entries.insert(
                    path.clone(),
                    LockEntry {
                        version: version.to_string(),
                        integrity: integrity.to_string(),
                    },
                );
            }
        }
        Ok(Lockfile {
            entries,
            dirty: false,
        })
    }

    pub fn to_toml_string(&self) -> String {
        let mut out = String::from("# Generated by aura. Do not edit manually.\n");
        for (path, e) in &self.entries {
            out.push_str(&format!(
                "\n[modules.\"{path}\"]\nversion = \"{}\"\nintegrity = \"{}\"\n",
                e.version, e.integrity
            ));
        }
        out
    }
}

/// Integrity-хэш содержимого модуля.
pub fn integrity_of(text: &str) -> String {
    use sha2::{Digest, Sha256};
    let digest = Sha256::digest(text.as_bytes());
    let mut hex = String::with_capacity(64);
    for b in digest {
        hex.push_str(&format!("{b:02x}"));
    }
    format!("sha256-{hex}")
}
