[package]
name = "aura-cli"
description = "CLI for the Aura configuration language: eval, check, fmt, add"
keywords = ["configuration", "config", "cli", "deterministic"]
categories = ["command-line-utilities", "config"]
readme = "../../README.md"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
authors.workspace = true

[[bin]]
name = "aura"
path = "src/main.rs"

[dependencies]
ariadne = "0.5"
aura-core = { path = "../aura-core" }
clap = { version = "4", features = ["derive", "string"] }
ureq = "2"
serde_json = "1"
